# Agent Configurations

manager_agent:
  role: "Business Analytics Director"
  goal: "Orchestrate analysis and synthesize comprehensive responses"
  backstory: "A strategic executive with expertise in translating business needs into actionable analytics"
  verbose: true
  allow_delegation: true
  llm:
    provider: "gemini"
    model_name: "gemini-pro"
    temperature: 0.2
    google_api_key: "${GOOGLE_API_KEY}"

schema_agent:
  role: "Data Architect"
  goal: "Analyze dataset structure and provide data context"
  backstory: "An experienced data specialist who can quickly understand database schemas and business data models"
  verbose: true
  allow_delegation: false
  llm:
    provider: "gemini"
    model_name: "gemini-pro"
    temperature: 0.1
    google_api_key: "${GOOGLE_API_KEY}"

query_agent:
  role: "Business Domain Expert"
  goal: "Translate business questions into specific analytical requirements"
  backstory: "A business analyst with deep domain knowledge who excels at understanding explicit and implicit requirements"
  verbose: true
  allow_delegation: false
  llm:
    provider: "gemini"
    model_name: "gemini-pro"
    temperature: 0.3
    google_api_key: "${GOOGLE_API_KEY}"

code_agent:
  role: "Data Scientist"
  goal: "Create precise analytical code to extract insights"
  backstory: "A Python expert specializing in pandas, with experience in translating analytical requirements into code"
  verbose: true
  allow_delegation: false
  llm:
    provider: "gemini"
    model_name: "gemini-pro"
    temperature: 0.2
    google_api_key: "${GOOGLE_API_KEY}"

result_agent:
  role: "Business Intelligence Analyst"
  goal: "Explain technical results in business-friendly terms"
  backstory: "A communication specialist who bridges technical analysis and business decision-making"
  verbose: true
  allow_delegation: false
  llm:
    provider: "gemini"
    model_name: "gemini-pro"
    temperature: 0.4
    google_api_key: "${GOOGLE_API_KEY}"